# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cameraFrameMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cameraFrameMsg.proto',
  package='robodogs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63\x61meraFrameMsg.proto\x12\x08robodogs\"1\n\x0e\x43\x61meraFrameMsg\x12\x13\n\x0b\x63\x61meraFrame\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\x05\x62\x06proto3')
)




_CAMERAFRAMEMSG = _descriptor.Descriptor(
  name='CameraFrameMsg',
  full_name='robodogs.CameraFrameMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameraFrame', full_name='robodogs.CameraFrameMsg.cameraFrame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='robodogs.CameraFrameMsg.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['CameraFrameMsg'] = _CAMERAFRAMEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraFrameMsg = _reflection.GeneratedProtocolMessageType('CameraFrameMsg', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAFRAMEMSG,
  __module__ = 'cameraFrameMsg_pb2'
  # @@protoc_insertion_point(class_scope:robodogs.CameraFrameMsg)
  ))
_sym_db.RegisterMessage(CameraFrameMsg)


# @@protoc_insertion_point(module_scope)
