protobuf: mockMsg.proto cameraFrameMsg.proto sensorMsg.proto firebaseMsg.proto
	protoc -I=./ --python_out=./ ./mockMsg.proto
	protoc -I=./ --python_out=./ ./cameraFrameMsg.proto
	protoc -I=./ --python_out=./ ./sensorMsg.proto
	protoc -I=./ --python_out=./ ./firebaseMsg.proto
