# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensorMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensorMsg.proto',
  package='robodog',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fsensorMsg.proto\x12\x07robodog\"\xa5\x01\n\tSensorMsg\x12.\n\tsentences\x18\x01 \x03(\x0b\x32\x1b.robodog.SensorMsg.Sentence\x1ah\n\x08Sentence\x12\x12\n\nconditions\x18\x01 \x03(\t\x12\x10\n\x08\x63ommands\x18\x02 \x03(\t\x12\x11\n\tquestions\x18\x03 \x03(\t\x12\x10\n\x08sentence\x18\x04 \x01(\t\x12\x11\n\tsentiment\x18\x05 \x01(\x02\x62\x06proto3')
)




_SENSORMSG_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='robodog.SensorMsg.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conditions', full_name='robodog.SensorMsg.Sentence.conditions', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commands', full_name='robodog.SensorMsg.Sentence.commands', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='questions', full_name='robodog.SensorMsg.Sentence.questions', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentence', full_name='robodog.SensorMsg.Sentence.sentence', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentiment', full_name='robodog.SensorMsg.Sentence.sentiment', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=194,
)

_SENSORMSG = _descriptor.Descriptor(
  name='SensorMsg',
  full_name='robodog.SensorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='robodog.SensorMsg.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SENSORMSG_SENTENCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=194,
)

_SENSORMSG_SENTENCE.containing_type = _SENSORMSG
_SENSORMSG.fields_by_name['sentences'].message_type = _SENSORMSG_SENTENCE
DESCRIPTOR.message_types_by_name['SensorMsg'] = _SENSORMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorMsg = _reflection.GeneratedProtocolMessageType('SensorMsg', (_message.Message,), dict(

  Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
    DESCRIPTOR = _SENSORMSG_SENTENCE,
    __module__ = 'sensorMsg_pb2'
    # @@protoc_insertion_point(class_scope:robodog.SensorMsg.Sentence)
    ))
  ,
  DESCRIPTOR = _SENSORMSG,
  __module__ = 'sensorMsg_pb2'
  # @@protoc_insertion_point(class_scope:robodog.SensorMsg)
  ))
_sym_db.RegisterMessage(SensorMsg)
_sym_db.RegisterMessage(SensorMsg.Sentence)


# @@protoc_insertion_point(module_scope)
